### ISSUE TITLE
Feature Request :: Snap Mouse to "assumed" next option

### ISSUE THREAD

**Issue by wachuwamekil** [Jslquintero/DialogUI#1]
This is an awesome reskin, I'm working on a configuration to make turtle more friendly with the steam deck.  Do you know if it is possible to snap the mouse cursor to the first item in each list similar to the loot.lua file?

Thought is ::
On available quests, snap to the first avail quest so you can easily click
On the quest dialog, snap to default "accept"
If the quest is already taken or isn't available snap to "goodbye"

Thanks!

**Comment by Jslquintero** [comment]
Sorry, I don't own a steam deck, anyway the addon only changes the vanilla texture as creating the whole environment from scratch would be very tedious. At first, I was creating it from scratch but due to lack of documentation and API functionality in this version of the game I don't see it as a good investment of time.
